# Generated by Django 4.2.3 on 2023-07-21 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options_blog_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-updated_at', '-created_at']},
        ),
    ]
